system.action.pathauto_update_alias_node:
  expected_config: {  }
  update_actions:
    add:
      configuration: {  }
system.action.pathauto_update_alias_user:
  expected_config: {  }
  update_actions:
    add:
      configuration: {  }
