chosen.settings:
  expected_config:
    jquery_selector: 'select#edit-field-partner, select#edit-field-categories'
  update_actions:
    change:
      jquery_selector: 'select#edit-field-partner, select#edit-field-categories, select#edit-field-topic'
