cohesion.sync.settings:
    expected_config:
      enabled_entity_types:
          image_style: image_style
          view: view
    update_actions:
      delete:
        enabled_entity_types:
          image_style: image_style
          view: view
