rabbit_hole.behavior_settings.taxonomy_vocabulary_audience:
  expected_config:
    allow_override: 1
  update_actions:
    change:
      allow_override: 0
rabbit_hole.behavior_settings.taxonomy_vocabulary_business_structure:
  expected_config:
    allow_override: 1
  update_actions:
    change:
      allow_override: 0
rabbit_hole.behavior_settings.taxonomy_vocabulary_business_topic:
  expected_config:
    allow_override: 1
  update_actions:
    change:
      allow_override: 0
rabbit_hole.behavior_settings.taxonomy_vocabulary_categories:
  expected_config:
    allow_override: 1
  update_actions:
    change:
      allow_override: 0
rabbit_hole.behavior_settings.taxonomy_vocabulary_content_topology:
  expected_config:
    allow_override: 1
  update_actions:
    change:
      allow_override: 0
rabbit_hole.behavior_settings.taxonomy_vocabulary_designation:
  expected_config:
    allow_override: 1
  update_actions:
    change:
      allow_override: 0
rabbit_hole.behavior_settings.taxonomy_vocabulary_document_type:
  expected_config:
    allow_override: 1
  update_actions:
    change:
      allow_override: 0
rabbit_hole.behavior_settings.taxonomy_vocabulary_finance_type:
  expected_config:
    allow_override: 1
  update_actions:
    change:
      allow_override: 0
rabbit_hole.behavior_settings.taxonomy_vocabulary_image_type:
  expected_config:
    allow_override: 1
  update_actions:
    change:
      allow_override: 0
rabbit_hole.behavior_settings.taxonomy_vocabulary_partner:
  expected_config:
    allow_override: 1
  update_actions:
    change:
      allow_override: 0
rabbit_hole.behavior_settings.taxonomy_vocabulary_programme:
  expected_config:
    allow_override: 1
  update_actions:
    change:
      allow_override: 0
rabbit_hole.behavior_settings.taxonomy_vocabulary_region:
  expected_config:
    allow_override: 1
  update_actions:
    change:
      allow_override: 0
rabbit_hole.behavior_settings.taxonomy_vocabulary_signature_campaigns:
  expected_config:
    allow_override: 1
  update_actions:
    change:
      allow_override: 0
rabbit_hole.behavior_settings.taxonomy_vocabulary_team_member_group:
  expected_config:
    allow_override: 1
  update_actions:
    change:
      allow_override: 0
rabbit_hole.behavior_settings.taxonomy_vocabulary_video_type:
  expected_config:
    allow_override: 1
  update_actions:
    change:
      allow_override: 0
rabbit_hole.behavior_settings.taxonomy_vocabulary_finance_amount_of_finance:
  expected_config:
    allow_override: 1
  update_actions:
    change:
      allow_override: 0
rabbit_hole.behavior_settings.taxonomy_vocabulary_finance_assets:
  expected_config:
    allow_override: 1
  update_actions:
    change:
      allow_override: 0
rabbit_hole.behavior_settings.taxonomy_vocabulary_finance_business_stage:
  expected_config:
    allow_override: 1
  update_actions:
    change:
      allow_override: 0
rabbit_hole.behavior_settings.taxonomy_vocabulary_finance_category:
  expected_config:
    allow_override: 1
  update_actions:
    change:
      allow_override: 0
rabbit_hole.behavior_settings.taxonomy_vocabulary_finance_profits:
  expected_config:
    allow_override: 1
  update_actions:
    change:
      allow_override: 0
rabbit_hole.behavior_settings.taxonomy_vocabulary_finance_reason_for_finance:
  expected_config:
    allow_override: 1
  update_actions:
    change:
      allow_override: 0
