rabbit_hole.behavior_settings.taxonomy_vocabulary_person_type:
  expected_config:
    allow_override: 1
  update_actions:
    change:
      allow_override: 0
rabbit_hole.behavior_settings.taxonomy_vocabulary_place_type:
  expected_config:
    allow_override: 1
  update_actions:
    change:
      allow_override: 0
