views.view.case_study_listing:
  expected_config: {  }
  update_actions:
    add:
      display:
        our_case_studies:
          display_options:
            defaults:
              title: false
            title: 'Success stories'
