core.entity_form_display.node.event.default:
  expected_config: {  }
  update_actions:
    change:
      content:
        field_content_owner:
          type: entity_reference_autocomplete
          weight: 24
field.field.node.event.field_teaser_text:
  expected_config: {  }
  update_actions:
    change:
      description: 'This Text will be used for teaser cards display but not on Detailed page'
