views.view.events:
  expected_config:
    display:
      default:
        display_options:
          row:
            options:
              view_mode: card_h4
  update_actions:
    change:
      display:
        default:
          display_options:
            row:
              options:
                view_mode: card
