rabbit_hole.behavior_settings.taxonomy_vocabulary_faq:
  expected_config:
    allow_override: 1
  update_actions:
    change:
      allow_override: 0
rabbit_hole.behavior_settings.taxonomy_vocabulary_faq_category:
  expected_config:
    allow_override: 1
  update_actions:
    change:
      allow_override: 0
rabbit_hole.behavior_settings.taxonomy_vocabulary_tags:
  expected_config:
    allow_override: 1
  update_actions:
    change:
      allow_override: 0
