core.entity_view_display.node.product.card_without_image:
  expected_config:
    content:
      field_teaser_text:
        label: above
  update_actions:
    change:
      content:
        field_teaser_text:
          label: hidden
core.entity_view_display.node.product.card_without_image_h3:
  expected_config:
    content:
      field_teaser_text:
        label: above
  update_actions:
    change:
      content:
        field_teaser_text:
          label: hidden
core.entity_view_display.node.product.card_without_image_h4:
  expected_config:
    content:
      field_teaser_text:
        label: above
  update_actions:
    change:
      content:
        field_teaser_text:
          label: hidden
