node.type.product:
  expected_config: {}
  update_actions:
    add:
      third_party_settings:
        node_title_help_text:
            title_help: 'H1,H2 Headings should be no longer than [10] words in length'
