core.entity_view_display.node.product.default:
  expected_config:
    content:
      field_layout_canvas:
        label: above
  update_actions:
    change:
      content:
        field_layout_canvas:
          label: hidden
