core.entity_view_display.media.video.default:
  expected_config:
    content:
      created:
        label: above
        region: content
        settings:
          custom_date_format: ''
          date_format: medium
          timezone: ''
        third_party_settings: {  }
        type: timestamp
        weight: 1
      field_video_caption:
        label: above
        weight: 3
      thumbnail:
        label: hidden
        region: content
        settings:
          image_link: ''
          image_loading:
            attribute: lazy
          image_style: thumbnail
          svg_attributes:
            height: null
            width: null
          svg_render_as_image: true
        third_party_settings: {  }
        type: image
        weight: 2
      uid:
        label: above
        region: content
        settings:
          link: true
        third_party_settings: {  }
        type: entity_reference_label
        weight: 0
    hidden:
      field_media_oembed_video: true
  update_actions:
    delete:
      content:
        created:
          label: above
          region: content
          settings:
            custom_date_format: ''
            date_format: medium
            timezone: ''
          third_party_settings: {  }
          type: timestamp
          weight: 1
        thumbnail:
          label: hidden
          region: content
          settings:
            image_link: ''
            image_loading:
              attribute: lazy
            image_style: thumbnail
            svg_attributes:
              height: null
              width: null
            svg_render_as_image: true
          third_party_settings: {  }
          type: image
          weight: 2
        uid:
          label: above
          region: content
          settings:
            link: true
          third_party_settings: {  }
          type: entity_reference_label
          weight: 0
      hidden:
        field_media_oembed_video: true
    add:
      hidden:
        created: true
        thumbnail: true
        uid: true
    change:
      content:
        field_media_oembed_video:
          label: hidden
          region: content
          settings:
            max_height: 459
            max_width: 816
          third_party_settings: {  }
          type: oembed
          weight: 0
        field_video_caption:
          label: hidden
          weight: 1
core.entity_view_display.media.video.embedded:
  expected_config:
    hidden:
      field_video_caption: true
  update_actions:
    delete:
      hidden:
        field_video_caption: true
