rabbit_hole.behavior_settings.taxonomy_vocabulary_business_stages:
  expected_config:
    allow_override: 1
  update_actions:
    change:
      allow_override: 0
rabbit_hole.behavior_settings.taxonomy_vocabulary_content_areas:
  expected_config:
    allow_override: 1
  update_actions:
    change:
      allow_override: 0
rabbit_hole.behavior_settings.taxonomy_vocabulary_finance_need:
  expected_config:
    allow_override: 1
  update_actions:
    change:
      allow_override: 0
rabbit_hole.behavior_settings.taxonomy_vocabulary_financial_variant:
  expected_config:
    allow_override: 1
  update_actions:
    change:
      allow_override: 0
rabbit_hole.behavior_settings.taxonomy_vocabulary_funding_type:
  expected_config:
    allow_override: 1
  update_actions:
    change:
      allow_override: 0
rabbit_hole.behavior_settings.taxonomy_vocabulary_investment_manager:
  expected_config:
    allow_override: 1
  update_actions:
    change:
      allow_override: 0
rabbit_hole.behavior_settings.taxonomy_vocabulary_investment_types:
  expected_config:
    allow_override: 1
  update_actions:
    change:
      allow_override: 0
rabbit_hole.behavior_settings.taxonomy_vocabulary_lender_schemes:
  expected_config:
    allow_override: 1
  update_actions:
    change:
      allow_override: 0
rabbit_hole.behavior_settings.taxonomy_vocabulary_partner_types:
  expected_config:
    allow_override: 1
  update_actions:
    change:
      allow_override: 0
rabbit_hole.behavior_settings.taxonomy_vocabulary_segment:
  expected_config:
    allow_override: 1
  update_actions:
    change:
      allow_override: 0
rabbit_hole.behavior_settings.taxonomy_vocabulary_stages:
  expected_config:
    allow_override: 1
  update_actions:
    change:
      allow_override: 0
