views.view.partners:
  expected_config: { }
  update_actions:
    change:
      display:
        partner_list:
          display_options:
            exposed_form:
              options:
                bef:
                  filter:
                    field_finance_type_target_id:
                      options_show_only_used: 1
                      options_show_only_used_filtered: 1
                    field_inv_types_target_id:
                      options_show_only_used: 1
                      options_show_only_used_filtered: 1
                    field_partner_sector_target_id:
                      options_show_only_used: 1
                      options_show_only_used_filtered: 1
                    field_partner_stages_target_id:
                      options_show_only_used: 1
                      options_show_only_used_filtered: 1
                    field_programme_target_id:
                      options_show_only_used: 1
                      options_show_only_used_filtered: 1
                    field_region_target_id:
                      options_show_only_used: 1
                      options_show_only_used_filtered: 1
                    tid:
                      options_show_only_used: 1
