-
  type: package
  source:
    path: ../config/site_studio_sync/pack_linked_feature_card
  options:
    extra-validation: false
-
  type: package
  source:
    path: ../config/site_studio_sync/pack_default_colors
  options:
    extra-validation: false
-
  type: package
  source:
    path: ../config/site_studio_sync/pack_bbi_colors
  options:
    extra-validation: false
-
  type: package
  source:
    path: ../config/site_studio_sync/pack_website_settings
  options:
    extra-validation: false
-
  type: package
  source:
    path: ../config/site_studio_sync/pack_all_layout_components
  options:
    extra-validation: false
-
  type: package
  source:
    path: ../config/site_studio_sync/pack_basic_components
  options:
    extra-validation: false
-
  type: package
  source:
    path: ../config/site_studio_sync/pack_base_styles
  options:
    extra-validation: false
-
  type: package
  source:
    path: ../config/site_studio_sync/pack_generic_custom_styles
  options:
    extra-validation: false
-
  type: package
  source:
    path: ../config/site_studio_sync/pack_custom_layout_styles
  options:
    extra-validation: false
-
  type: package
  source:
    path: ../config/site_studio_sync/pack_custom_heading_styles
  options:
    extra-validation: false
-
  type: package
  source:
    path: ../config/site_studio_sync/pack_custom_button_styles
  options:
    extra-validation: false
-
  type: package
  source:
    path: ../config/site_studio_sync/pack_other_custom_styles
  options:
    extra-validation: false
-
  type: package
  source:
    path: ../config/site_studio_sync/pack_component_categories
  options:
    extra-validation: false
-
  type: package
  source:
    path: ../config/site_studio_sync/pack_all_accordion_components
  options:
    extra-validation: false
-
  type: package
  source:
    path: ../config/site_studio_sync/pack_dynamic_components
  options:
    extra-validation: false
-
  type: package
  source:
    path: ../config/site_studio_sync/pack_icomoon_icons
  options:
    extra-validation: false
-
  type: package
  source:
    path: ../config/site_studio_sync/pack_card_components
  options:
    extra-validation: false
-
  type: package
  source:
    path: ../config/site_studio_sync/pack_slider_components
  options:
    extra-validation: false
-
  type: package
  source:
    path: ../config/site_studio_sync/pack_google_map_component
  options:
    extra-validation: false
-
  type: package
  source:
    path: ../config/site_studio_sync/pack_hero_component
  options:
    extra-validation: false
-
  type: package
  source:
    path: ../config/site_studio_sync/pack_read_more_component
  options:
    extra-validation: false
-
  type: package
  source:
    path: ../config/site_studio_sync/pack_header_and_footer_component
  options:
    extra-validation: false
-
  type: package
  source:
    path: ../config/site_studio_sync/pack_tab_components
  options:
    extra-validation: false
-
  type: package
  source:
    path: ../config/site_studio_sync/pack_node_page_templates
  options:
    extra-validation: false
-
  type: package
  source:
    path: ../config/site_studio_sync/pack_media_image_templates
  options:
    extra-validation: false
-
  type: package
  source:
    path: ../config/site_studio_sync/pack_master_templates
  options:
    extra-validation: false
-
  type: package
  source:
    path: ../config/site_studio_sync/pack_view_templates
  options:
    extra-validation: false
-
  type: package
  source:
    path: ../config/site_studio_sync/pack_menu_templates
  options:
    extra-validation: false
-
  type: package
  source:
    path: ../config/site_studio_sync/pack_helper_categories
  options:
    extra-validation: false
-
  type: package
  source:
    path: ../config/site_studio_sync/pack_helpers
  options:
    extra-validation: false
-
  type: package
  source:
    path: ../config/site_studio_sync/pack_style_guides
  options:
    extra-validation: false
-
  type: package
  source:
    path: ../config/site_studio_sync/pack_style_guides_manager
  options:
    extra-validation: false
-
  type: package
  source:
    path: ../config/site_studio_sync/pack_font_stacks_default
  options:
    extra-validation: false
-
  type: package
  source:
    path: ../config/site_studio_sync/pack_scss_variables
  options:
    extra-validation: false
-
  type: package
  source:
    path: ../config/site_studio_sync/pack_bbb_fonts
  options:
    extra-validation: false
-
  type: package
  source:
    path: ../config/site_studio_sync/pack_aurora_foundations
  options:
    extra-validation: false
