field.storage.node.field_hero_background_pattern:
  expected_config: {  }
  update_actions:
    change:
      settings:
        allowed_values:
          - value: factory-blue
            label: 'Factory blue with lightbeam device'
          - value: ceramic
            label: 'Ceramic with lightbeam device'
          - value: lab-blue
            label: 'Laboratory Blue with lightbeam device'
          - value: ink-factory-blue
            label: 'Ink Blue with lightbeam device'
          - value: bbi-light
            label: 'BBI Light with lightbeam device'
          - value: bbi-dark
            label: 'BBI Dark with lightbeam device'
          - value: bpc-image
            label: 'BPC Background Image'
