views.view.news:
  expected_config: {  }
  update_actions:
    add:
      display:
        news_list:
          cache_metadata:
            contexts:
              - 'languages:language_content'
              - 'languages:language_interface'
              - url
              - url.query_args
              - 'url.query_args:sort_by'
              - 'url.query_args:sort_order'
              - user
              - 'user.node_grants:view'
              - user.permissions
            max-age: -1
            tags: {  }
          display_options:
            arguments: {  }
            css_class: views-list-content-container
            defaults:
              arguments: false
              css_class: false
              exposed_form: false
              filter_groups: false
              filters: false
              header: false
              pager: false
              row: false
              sorts: false
              style: false
              use_ajax: false
            display_description: ''
            display_extenders: {  }
            exposed_block: true
            exposed_form:
              options:
                bef:
                  filter:
                    field_region_target_id:
                      advanced:
                        collapsible: true
                        is_secondary: false
                        rewrite:
                          filter_rewrite_values: ''
                        sort_options: false
                      display_inline: false
                      plugin_id: bef
                      select_all_none: false
                      select_all_none_nested: false
                    nodes_month:
                      advanced:
                        collapsible: true
                        is_secondary: false
                        rewrite:
                          filter_rewrite_values: ''
                      plugin_id: default
                    nodes_year:
                      advanced:
                        collapsible: true
                        is_secondary: false
                        rewrite:
                          filter_rewrite_values: ''
                      plugin_id: default
                  general:
                    allow_secondary: false
                    autosubmit: true
                    autosubmit_exclude_textfield: false
                    autosubmit_hide: false
                    autosubmit_textfield_delay: 500
                    input_required: false
                    reset_button_always_show: true
                    secondary_label: 'Advanced options'
                    secondary_open: false
                  sort:
                    advanced:
                      collapsible: false
                      collapsible_label: 'Sort options'
                      combine: true
                      combine_rewrite: "Most Recent Desc|Most Recent\r\nMost Recent Asc|Oldest first"
                      is_secondary: false
                      reset: false
                      reset_label: ''
                    plugin_id: default
                expose_sort_order: true
                exposed_sorts_label: 'Sort by'
                reset_button: true
                reset_button_label: 'Reset all filters'
                sort_asc_label: Asc
                sort_desc_label: Desc
                submit_button: 'Apply filters'
                text_input_required: 'Select any filter and click on Apply to see results'
                text_input_required_format: filtered_html
              type: bef
            filter_groups:
              groups:
                1: AND
              operator: AND
            filters:
              field_region_target_id:
                admin_label: ''
                error_message: true
                expose:
                  description: ''
                  identifier: region
                  label: Region
                  multiple: true
                  operator: field_region_target_id_op
                  operator_id: field_region_target_id_op
                  operator_limit_selection: false
                  operator_list: {  }
                  reduce: false
                  remember: false
                  remember_roles:
                    administrator: '0'
                    anonymous: '0'
                    authenticated: authenticated
                    bankers: '0'
                    content_administrator: '0'
                    content_author: '0'
                    content_editor: '0'
                    content_factory: '0'
                    developer: '0'
                    site_builder: '0'
                    user_administrator: '0'
                  required: false
                  use_operator: false
                exposed: true
                field: field_region_target_id
                group: 1
                group_info:
                  default_group: All
                  default_group_multiple: {  }
                  description: ''
                  group_items: {  }
                  identifier: ''
                  label: ''
                  multiple: false
                  optional: true
                  remember: false
                  widget: select
                group_type: group
                hierarchy: false
                id: field_region_target_id
                is_grouped: false
                limit: true
                operator: or
                plugin_id: taxonomy_index_tid
                reduce_duplicates: false
                relationship: none
                table: node__field_region
                type: select
                value: {  }
                vid: region
              nodes_month:
                admin_label: ''
                entity_type: node
                expose:
                  description: ''
                  identifier: month
                  label: Month
                  multiple: true
                  operator: nodes_month_op
                  operator_id: ''
                  operator_limit_selection: false
                  operator_list: {  }
                  remember: false
                  remember_roles:
                    administrator: '0'
                    anonymous: '0'
                    authenticated: authenticated
                    bankers: '0'
                    content_administrator: '0'
                    content_author: '0'
                    content_editor: '0'
                    content_factory: '0'
                    developer: '0'
                    site_builder: '0'
                    user_administrator: '0'
                  required: false
                  use_operator: false
                exposed: true
                field: nodes_month
                field_name: created
                group: 1
                group_info:
                  default_group: All
                  default_group_multiple: {  }
                  description: ''
                  group_items: {  }
                  identifier: ''
                  label: ''
                  multiple: false
                  optional: true
                  remember: false
                  widget: select
                group_type: group
                id: nodes_month
                is_grouped: false
                node_month: ''
                operator: '='
                plugin_id: month_date_filter
                relationship: none
                table: node_field_data
                value: ''
              nodes_year:
                admin_label: ''
                entity_type: node
                expose:
                  description: ''
                  identifier: year
                  label: Year
                  multiple: true
                  operator: nodes_year_op
                  operator_id: ''
                  operator_limit_selection: false
                  operator_list: {  }
                  remember: false
                  remember_roles:
                    administrator: '0'
                    anonymous: '0'
                    authenticated: authenticated
                    bankers: '0'
                    content_administrator: '0'
                    content_author: '0'
                    content_editor: '0'
                    content_factory: '0'
                    developer: '0'
                    site_builder: '0'
                    user_administrator: '0'
                  required: false
                  use_operator: false
                exposed: true
                field: nodes_year
                field_name: created
                group: 1
                group_info:
                  default_group: All
                  default_group_multiple: {  }
                  description: ''
                  group_items: {  }
                  identifier: ''
                  label: ''
                  multiple: false
                  optional: true
                  remember: false
                  widget: select
                group_type: group
                id: nodes_year
                is_grouped: false
                node_year: ''
                operator: '='
                plugin_id: year_date_filter
                relationship: none
                table: node_field_data
                value: ''
                year_from: '2012'
                year_until: '2022'
              status:
                entity_field: status
                entity_type: node
                expose:
                  operator: ''
                  operator_limit_selection: false
                  operator_list: {  }
                field: status
                group: 1
                id: status
                plugin_id: boolean
                table: node_field_data
                value: '1'
              type:
                entity_field: type
                entity_type: node
                expose:
                  operator_limit_selection: false
                  operator_list: {  }
                field: type
                group: 1
                id: type
                plugin_id: bundle
                table: node_field_data
                value:
                  news: news
            header:
              result:
                admin_label: ''
                content: 'Showing @start - @end of @total results'
                empty: false
                field: result
                group_type: group
                id: result
                plugin_id: result
                relationship: none
                table: views
            pager:
              options:
                expose:
                  items_per_page: false
                  items_per_page_label: 'Items per page'
                  items_per_page_options: '5, 10, 25, 50'
                  items_per_page_options_all: false
                  items_per_page_options_all_label: '- All -'
                  offset: false
                  offset_label: Offset
                id: 0
                items_per_page: 10
                offset: 0
                quantity: 5
                tags:
                  first: '« First'
                  last: 'Last »'
                  next: 'Next ›'
                  previous: '‹ Previous'
                total_pages: null
              type: full
            path: news
            row:
              options:
                relationship: none
                view_mode: card
              type: 'entity:node'
            sorts:
              created:
                admin_label: ''
                entity_field: created
                entity_type: node
                expose:
                  field_identifier: created
                  label: 'Most Recent'
                exposed: true
                field: created
                granularity: second
                group_type: group
                id: created
                order: DESC
                plugin_id: date
                relationship: none
                table: node_field_data
            style:
              options:
                master_template: __none__
                views_template: view_tpl_news_list
              type: cohesion_layout
            use_ajax: true
          display_plugin: page
          display_title: 'News list'
          id: news_list
          position: 2
    change:
      display:
        default:
          display_options:
            sorts:
              created:
                expose:
                  field_identifier: created
                  label: 'Authored on'
