core.entity_form_display.node.news.default:
  expected_config: {}
  update_actions:
    add:
      content:
        field_image:
          region: content
          settings:
            media_types: {  }
          third_party_settings: {  }
          type: media_library_widget
          weight: 18
    change:
      content:
        field_layout_canvas:
          weight: 19
        field_quick_links:
          weight: 20
