views.view.news:
  expected_config: {  }
  update_actions:
    add:
      display:
        news_list:
          display_options:
            filters:
              created:
                admin_label: ''
                entity_field: created
                entity_type: node
                expose:
                  description: ''
                  identifier: ''
                  label: ''
                  max_placeholder: ''
                  min_placeholder: ''
                  multiple: false
                  operator: ''
                  operator_id: ''
                  operator_limit_selection: false
                  operator_list: {  }
                  placeholder: ''
                  remember: false
                  remember_roles:
                    authenticated: authenticated
                  required: false
                  use_operator: false
                exposed: false
                field: created
                group: 1
                group_info:
                  default_group: All
                  default_group_multiple: {  }
                  description: ''
                  group_items: {  }
                  identifier: ''
                  label: ''
                  multiple: false
                  optional: true
                  remember: false
                  widget: select
                group_type: group
                id: created
                is_grouped: false
                operator: '>='
                plugin_id: date
                relationship: none
                table: node_field_data
                value:
                  max: ''
                  min: ''
                  type: offset
                  value: '-5 years'
