taxonomy.vocabulary.partner:
  expected_config: {  }
  update_actions:
    change:
      name: 'Fund Managers'
field.field.node.case_study.field_partner:
  expected_config: {  }
  update_actions:
    change:
      label: 'Fund Managers'
