core.entity_view_display.node.article.card:
  expected_config:
    content:
      field_teaser_text:
        type: basic_string
  update_actions:
    add:
      hidden:
        footnotes_group: true
    change:
      content:
        field_teaser_text:
          type: text_default
core.entity_view_display.node.article.card_h2:
  expected_config:
    content:
      field_teaser_text:
        type: basic_string
  update_actions:
    add:
      hidden:
        footnotes_group: true
    change:
      content:
        field_teaser_text:
          type: text_default
core.entity_view_display.node.article.card_h4:
  expected_config:
    content:
      field_teaser_text:
        type: basic_string
  update_actions:
    add:
      hidden:
        footnotes_group: true
    change:
      content:
        field_teaser_text:
          type: text_default
core.entity_view_display.node.article.horizontal_card:
  expected_config:
    content:
      field_teaser_text:
        type: basic_string
  update_actions:
    add:
      hidden:
        footnotes_group: true
    change:
      content:
        field_teaser_text:
          type: text_default
core.entity_view_display.node.article.horizontal_card_h2:
  expected_config:
    content:
      field_teaser_text:
        type: basic_string
  update_actions:
    add:
      hidden:
        footnotes_group: true
    change:
      content:
        field_teaser_text:
          type: text_default
core.entity_view_display.node.article.horizontal_card_h4:
  expected_config:
    content:
      field_teaser_text:
        type: basic_string
  update_actions:
    add:
      hidden:
        footnotes_group: true
    change:
      content:
        field_teaser_text:
          type: text_default
core.entity_view_display.node.article.related_content:
  expected_config:
    content:
      field_teaser_text:
        type: basic_string
  update_actions:
    add:
      hidden:
        footnotes_group: true
    change:
      content:
        field_teaser_text:
          type: text_default
core.entity_view_display.node.case_study.card:
  expected_config:
    content:
      field_teaser_text:
        type: basic_string
  update_actions:
    add:
      hidden:
        footnotes_group: true
    change:
      content:
        field_teaser_text:
          type: text_default
core.entity_view_display.node.case_study.card_h2:
  expected_config:
    content:
      field_teaser_text:
        type: basic_string
  update_actions:
    add:
      hidden:
        footnotes_group: true
    change:
      content:
        field_teaser_text:
          type: text_default
core.entity_view_display.node.case_study.card_h4:
  expected_config:
    content:
      field_teaser_text:
        type: basic_string
  update_actions:
    add:
      hidden:
        footnotes_group: true
    change:
      content:
        field_teaser_text:
          type: text_default
core.entity_view_display.node.case_study.horizontal_card:
  expected_config:
    content:
      field_teaser_text:
        type: basic_string
  update_actions:
    change:
      content:
        field_teaser_text:
          type: text_default
core.entity_view_display.node.case_study.horizontal_card_h2:
  expected_config:
    content:
      field_teaser_text:
        type: basic_string
  update_actions:
    add:
      hidden:
        footnotes_group: true
    change:
      content:
        field_teaser_text:
          type: text_default
core.entity_view_display.node.case_study.horizontal_card_h4:
  expected_config:
    content:
      field_teaser_text:
        type: basic_string
  update_actions:
    add:
      hidden:
        footnotes_group: true
    change:
      content:
        field_teaser_text:
          type: text_default
core.entity_view_display.node.case_study.related_content:
  expected_config:
    content:
      field_teaser_text:
        type: basic_string
  update_actions:
    change:
      content:
        field_teaser_text:
          type: text_default
core.entity_view_display.node.news.featured:
  expected_config:
    content:
      field_teaser_text:
        type: basic_string
  update_actions:
    add:
      hidden:
        footnotes_group: true
    change:
      content:
        field_teaser_text:
          type: text_default
core.entity_view_display.node.news.featured_h2:
  expected_config:
    content:
      field_teaser_text:
        type: basic_string
  update_actions:
    add:
      hidden:
        footnotes_group: true
    change:
      content:
        field_teaser_text:
          type: text_default
core.entity_view_display.node.news.featured_h4:
  expected_config:
    content:
      field_teaser_text:
        type: basic_string
  update_actions:
    add:
      hidden:
        footnotes_group: true
    change:
      content:
        field_teaser_text:
          type: text_default
core.entity_view_display.node.news.horizontal_card:
  expected_config:
    content:
      field_teaser_text:
        type: basic_string
  update_actions:
    add:
      hidden:
        footnotes_group: true
    change:
      content:
        field_teaser_text:
          type: text_default
core.entity_view_display.node.news.horizontal_card_h2:
  expected_config:
    content:
      field_teaser_text:
        type: basic_string
  update_actions:
    add:
      hidden:
        footnotes_group: true
    change:
      content:
        field_teaser_text:
          type: text_default
core.entity_view_display.node.news.horizontal_card_h4:
  expected_config:
    content:
      field_teaser_text:
        type: basic_string
  update_actions:
    add:
      hidden:
        footnotes_group: true
    change:
      content:
        field_teaser_text:
          type: text_default
core.entity_view_display.node.product.card:
  expected_config:
    content:
      field_teaser_text:
        settings:
          more_class: more-link
          more_link: false
          more_text: More
          summary_handler: full
          trim_length: 600
          trim_options: {  }
          trim_suffix: ''
          trim_type: chars
          wrap_class: trimmed
          wrap_output: false
        type: smart_trim
  update_actions:
    delete:
      content:
        field_teaser_text:
          settings:
            more_class: more-link
            more_link: false
            more_text: More
            summary_handler: full
            trim_length: 600
            trim_options: {  }
            trim_suffix: ''
            trim_type: chars
            wrap_class: trimmed
            wrap_output: false
    add:
      hidden:
        footnotes_group: true
    change:
      content:
        field_teaser_text:
          settings: {  }
          type: text_default
core.entity_view_display.node.product.card_h2:
  expected_config:
    content:
      field_teaser_text:
        settings:
          more_class: more-link
          more_link: false
          more_text: More
          summary_handler: full
          trim_length: 600
          trim_options:
            text: false
            trim_zero: false
          trim_suffix: ''
          trim_type: chars
          wrap_class: trimmed
          wrap_output: false
        type: smart_trim
  update_actions:
    delete:
      content:
        field_teaser_text:
          settings:
            more_class: more-link
            more_link: false
            more_text: More
            summary_handler: full
            trim_length: 600
            trim_options:
              text: false
              trim_zero: false
            trim_suffix: ''
            trim_type: chars
            wrap_class: trimmed
            wrap_output: false
    add:
      hidden:
        footnotes_group: true
    change:
      content:
        field_teaser_text:
          settings: {  }
          type: text_default
core.entity_view_display.node.product.card_h4:
  expected_config:
    content:
      field_teaser_text:
        settings:
          more_class: more-link
          more_link: false
          more_text: More
          summary_handler: full
          trim_length: 600
          trim_options: {  }
          trim_suffix: ''
          trim_type: chars
          wrap_class: trimmed
          wrap_output: false
        type: smart_trim
  update_actions:
    delete:
      content:
        field_teaser_text:
          settings:
            more_class: more-link
            more_link: false
            more_text: More
            summary_handler: full
            trim_length: 600
            trim_options: {  }
            trim_suffix: ''
            trim_type: chars
            wrap_class: trimmed
            wrap_output: false
    add:
      hidden:
        footnotes_group: true
    change:
      content:
        field_teaser_text:
          settings: {  }
          type: text_default
core.entity_view_display.node.product.card_without_image:
  expected_config:
    content:
      field_teaser_text:
        type: basic_string
  update_actions:
    add:
      hidden:
        footnotes_group: true
    change:
      content:
        field_teaser_text:
          type: text_default
core.entity_view_display.node.product.card_without_image_h3:
  expected_config:
    content:
      field_teaser_text:
        type: basic_string
  update_actions:
    add:
      hidden:
        footnotes_group: true
    change:
      content:
        field_teaser_text:
          type: text_default
core.entity_view_display.node.product.card_without_image_h4:
  expected_config:
    content:
      field_teaser_text:
        type: basic_string
  update_actions:
    add:
      hidden:
        footnotes_group: true
    change:
      content:
        field_teaser_text:
          type: text_default
core.entity_view_display.node.research_and_publication.default:
  expected_config:
    content:
      field_teaser_text:
        type: basic_string
  update_actions:
    add:
      hidden:
        footnotes_group: true
    change:
      content:
        field_teaser_text:
          type: text_default
