user.role.content_editor:
  expected_config: {  }
  update_actions:
    add:
      permissions:
        - 'access content'
        - 'administer component content'
        - 'clone node entity'
        - 'create article content'
        - 'create case_study content'
        - 'create event content'
        - 'create landing_page content'
        - 'create news content'
        - 'create page content'
        - 'create product content'
        - 'create team_member content'
        - 'delete any document media'
        - 'delete any video media'
        - 'delete own article content'
        - 'delete own case_study content'
        - 'delete own event content'
        - 'delete own landing_page content'
        - 'delete own news content'
        - 'delete own page content'
        - 'delete own product content'
        - 'delete own team_member content'
        - 'edit any article content'
        - 'edit any case_study content'
        - 'edit any document media'
        - 'edit any event content'
        - 'edit any landing_page content'
        - 'edit any news content'
        - 'edit any page content'
        - 'edit any product content'
        - 'edit any team_member content'
        - 'edit any video media'
        - 'edit own article content'
        - 'edit own case_study content'
        - 'edit own event content'
        - 'edit own landing_page content'
        - 'edit own news content'
        - 'edit own page content'
        - 'edit own product content'
        - 'edit own team_member content'
        - 'view all revisions'
        - 'view article revisions'
        - 'view case_study revisions'
        - 'view event revisions'
        - 'view landing_page revisions'
        - 'view news revisions'
        - 'view own unpublished content'
        - 'view page revisions'
        - 'view product revisions'
        - 'view team_member revisions'
        - 'create image media'
        - 'create document media'
        - 'create video media'
        - 'delete own image media'
        - 'delete own document media'
        - 'delete own video media'
        - 'edit any image media'
        - 'edit any document media'
        - 'edit any video media'
        - 'edit own document media'
        - 'edit own video media'
        - 'edit own image media'
        - 'create media'
        - 'update media'
        - 'view media'
        - 'view own unpublished media'
        - 'update content translations'
